// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface UserMember {
  id: number;
  label: null;
  member: Member;
}

export interface Member {
  id: number;
  chinese_name: string;
  english_name: string;
  avatar_url: string;
  avatar_thumb_url: string;
  token: string;
  type: string;
  company: Company;
}

export interface Company {
  id: number;
  chinese_name: string;
  english_name: string;
  token: string;
}
