export declare function superGroupGetMessage(groupID: string, messageId: string): Promise<string>;
export declare function superGroupGetMultipleMessage(messageIdsStr: string, groupID: string): Promise<string>;
export declare function getSuperGroupNormalMsgSeq(groupID: string): Promise<string>;
export declare function superGroupGetNormalMinSeq(groupID: string): Promise<string>;
export declare function superGroupUpdateMessageTimeAndStatus(groupID: string, clientMsgID: string, serverMsgID: string, sendTime: number, status: number): Promise<string>;
export declare function superGroupUpdateMessage(groupID: string, clientMsgID: string, messageStr: string): Promise<string>;
export declare function superGroupUpdateColumnsMessage(clientMsgID: string, groupID: string, messageStr: string): Promise<string>;
export declare function superGroupInsertMessage(messageStr: string, groupID: string): Promise<string>;
export declare function superGroupBatchInsertMessageList(messageListStr: string, groupID: string): Promise<string>;
export declare function superGroupGetMessageListNoTime(groupID: string, sessionType: number, count: number, isReverse?: boolean): Promise<string>;
export declare function superGroupGetMessageList(groupID: string, sessionType: number, count: number, startTime: number, isReverse?: boolean): Promise<string>;
export declare function superGroupDeleteAllMessage(groupID: string): Promise<string>;
export declare function superGroupSearchMessageByKeyword(contentTypeStr: string, keywordListStr: string, keywordListMatchType: number, sourceID: string, startTime: number, endTime: number, sessionType: number, offset: number, count: number): Promise<string>;
export declare function superGroupSearchMessageByContentType(contentTypeStr: string, sourceID: string, startTime: number, endTime: number, sessionType: number, offset: number, count: number): Promise<string>;
export declare function superGroupSearchMessageByContentTypeAndKeyword(contentTypeStr: string, keywordListStr: string, keywordListMatchType: number, startTime: number, endTime: number, groupID: string): Promise<string>;
export declare function superGroupUpdateMessageStatusBySourceID(sourceID: string, status: string, sessionType: number): Promise<string>;
export declare function superGroupGetSendingMessageList(groupID: string): Promise<string>;
export declare function superGroupUpdateGroupMessageHasRead(msgIDListStr: string, groupID: string): Promise<string>;
export declare function superGroupGetMsgSeqByClientMsgID(clientMsgID: string, groupID: string): Promise<string>;
export declare function superGroupUpdateMsgSenderFaceURLAndSenderNickname(sendID: string, faceURL: string, nickname: string, sessionType: number, groupID: string): Promise<string>;
