export enum messageTypes {
  TEXTMESSAGE = 101,
  PICTUREMESSAGE = 102,
  VOICEMESSAGE = 103,
  VIDEOMESSAGE = 104,
  FILEMESSAGE = 105,
  ATTEXTMESSAGE = 106,
  MERGERMESSAGE = 107,
  CARDMESSAGE = 108,
  LOCATIONMESSAGE = 109,
  CUSTOMMESSAGE = 110,
  REVOKEMESSAGE = 111,
  HASREADRECEIPTMESSAGE = 112,
  TYPINGMESSAGE = 113,
  QUOTEMESSAGE = 114,
}

export enum tipsTypes {
  REVOKEMESSAGE = 111,
  FRIENDAPPLICATIONAPPROVED = 1201, //add_friend_response
  FRIENDAPPLICATIONREJECTED = 1202, //add_friend_response
  FRIENDAPPLICATIONADDED = 1203, //add_friend
  FRIENDADDED = 1204,
  FRIENDDELETED = 1205, //delete_friend
  FRIENDREMARKSET = 1206, //set_friend_remark?
  BLACKADDED = 1207, //add_black
  BLACKDELETED = 1208, //remove_black
  SELFINFOUPDATED = 1303, //SetSelfInfoTip
  GROUPCREATED = 1501,
  GROUPINFOUPDATED = 1502,
  JOINGROUPAPPLICATIONADDED = 1503,
  MEMBERQUIT = 1504,
  GROUPAPPLICATIONACCEPTED = 1505,
  GROUPAPPLICATIONREJECTED = 1506,
  GROUPOWNERTRANSFERRED = 1507,
  MEMBERKICKED = 1508,
  MEMBERINVITED = 1509,
  MEMBERENTER = 1510,
}

export const nomalMessageTypes = [
  messageTypes.TEXTMESSAGE,
  messageTypes.ATTEXTMESSAGE,
  messageTypes.CARDMESSAGE,
  messageTypes.MERGERMESSAGE,
  messageTypes.LOCATIONMESSAGE,
  messageTypes.CUSTOMMESSAGE,
  messageTypes.REVOKEMESSAGE,
  messageTypes.HASREADRECEIPTMESSAGE,
  messageTypes.TYPINGMESSAGE,
  messageTypes.QUOTEMESSAGE,
];

export const notOssMessageTypes = [messageTypes.PICTUREMESSAGE, messageTypes.VIDEOMESSAGE, messageTypes.VOICEMESSAGE, messageTypes.FILEMESSAGE];

export enum SessionType {
  SINGLECVE = 1,
  GROUPCVE = 2,
}
